services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multiply_laravel
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - multiply_net
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: multiply_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - multiply_net
    depends_on:
      - app

  db:
    image: mariadb:latest
    container_name: multiply_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: multiply_quiz_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - multiply_net

  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - "8888:9000"   # HTTP
      - "9443:9443"   # HTTPS
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - multiply_net

volumes:
  db_data:
  portainer_data:

networks:
  multiply_net:
    driver: bridge
